### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by edlee2121** [kubegene/kubegene#30]
Hi folks,

Very cool project!

Jeremy Lewi (Google Kubeflow) mentioned your project to us. We collaborate with Jeremy and the Kubeflow team because they use Argo (https://github.com/argoproj/argo) as their workflow engine for Kubernetes.

Please let us know if you may find Argo useful for your project as well.

Regards,
Ed

**Comment by tsjsdbd** [comment]
hi
We have analyzed the Argo project before starting KubeGene，And thought that it was not the best practice for concurrency task. for example：

if the actual jobs like this：
![image](https://user-images.githubusercontent.com/7219402/48607652-7e7c5100-e9bc-11e8-8de9-240269de03ac.png)

if use Argo, it need describe the whole DAG of job，but if use KubeGene（use KubeDag-engine），it just need describe the main workflow like this：
![image](https://user-images.githubusercontent.com/7219402/48607797-b388a380-e9bc-11e8-8ec6-04c52d0ec35e.png)

differents is:
1. it need just one job description， for variant concurrency tasks (many Container with same image, but each one is running different command)。
2. it support depends type when concurrency。like “whole” or “iterate”。

so，we build another workflow engine。

**Comment by edlee2121** [comment]
Thanks for your detailed reply! We're currently discussing whether some of these use cases may be better addressed by leveraging Argo Events (https://github.com/argoproj/argo-events).

If you will be in KubeCon Seattle, please drop by our booth!

Regards,
Ed

**Comment by kevin-wangzefeng** [comment]
Thanks @edlee2121, we'd be happy to see if Argo could integrate with KubeGene, though there are some gaps today.

I will be (probably) at KubeCon Seattle, let's find some time to talk :-)

**Comment by edlee2121** [comment]
Cool, would be good to better understand your use cases.
I won't be at KubeCon myself, but I've let @jessesuen and @mukulikak know to expect you :-)
