### ISSUE TITLE
submit execution error:the server could not find the requested resource

### ISSUE THREAD

**Issue by xllbit** [kubegene/kubegene#31]
When I submited the workflow, I met a mistake:
`Error: submit execution error: the server could not find the requested resource (post executions.execution.kubegene.io)`
the command I used is as follows:
`genectl sub workflow example/simple-sample/simple-sample.yaml --tool-repo example/tools/` 
what does the error means and how can I solve it?

**Comment by hzxuzhonghu** [comment]
@xllbit  i think you donot have crd installed.    

check by` kubectl get crd`

**Comment by hzxuzhonghu** [comment]
@xllbit Any info from `kube-dag-bc4f6bf68-grrpl ` logs?

**Comment by hzxuzhonghu** [comment]
It seems your kubedag pod is not ready.

**Comment by hzxuzhonghu** [comment]
logs can be fetched by `kubectl logs kube-dag-bc4f6bf68-grrpl`

**Comment by xllbit** [comment]
@hzxuzhonghu 
Thank you for your reply. I tried with the "describe" command this morning, and the following is the output.
`root@kube-X580-G30:/usr/local/go/src/kubegene.io/kubegene# kubectl describe pod 
kube-dag-bc4f6bf68-grrplName:           kube-dag-bc4f6bf68-grrpl
Namespace:      default
Node:           minikube/10.0.2.15
Start Time:     Thu, 27 Dec 2018 18:58:26 +0800
Labels:         kube-dag=test
                pod-template-hash=670926924
Annotations:    <none>
Status:         Pending
IP:             172.17.0.4
Controlled By:  ReplicaSet/kube-dag-bc4f6bf68
Containers:
  kube-dag:
    Container ID:  
    Image:         kube-dag:v1
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=4
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:
      MY_NAME:       kube-dag-bc4f6bf68-grrpl (v1:metadata.name)
      MY_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dag-token-f7cfk (r
o)Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  kube-dag-token-f7cfk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-dag-token-f7cfk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                   From               Message
  ----     ------   ----                  ----               -------
  Normal   Pulling  34m (x178 over 15h)   kubelet, minikube  pulling image "kube
-dag:v1"  Warning  Failed   14m (x3895 over 15h)  kubelet, minikube  Error: ImagePullBac
kOff  Normal   BackOff  4m (x3938 over 15h)   kubelet, minikube  Back-off pulling im
age "kube-dag:v1"`
as your said, the kubedag pod was not ready.
However, when I tried the command "./hack/local-up-kubedag.sh" just a moment ago, it looks ok.
`root@kube-X580-G30:/usr/local/go/src/kubegene.io/kubegene# ./hack/local-up-kubed
ag.sh mkdir -p bin
CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o ./bin/k
ube-dag ./cmd/kube-dagWARN[0000] Unable to use system certificate pool: requires building with go 1.7 
or later Sending build context to Docker daemon 86.83 MB
Step 1/3 : FROM alpine
latest: Pulling from library/alpine
cd784148e348: Pull complete 
Digest: sha256:46e71df1e5191ab8b8034c5189e325258ec44ea739bba1e5645cff83c9048ff1
Status: Downloaded newer image for alpine:latest
 ---> 3f53bb00af94
Step 2/3 : COPY ./bin/kube-dag /usr/local/bin
 ---> 5c4feb918de6
Step 3/3 : ENTRYPOINT ["/usr/local/bin/kube-dag"]
 ---> Running in b4a506469729
Removing intermediate container b4a506469729
 ---> a722378e5157
Successfully built a722378e5157
Successfully tagged kube-dag:v1
deployment.apps "kube-dag" created
Error from server (AlreadyExists): error when creating "./deploy/setup-kubedag.y
aml": serviceaccounts "kube-dag" already existsError from server (AlreadyExists): error when creating "./deploy/setup-kubedag.y
aml": clusterroles.rbac.authorization.k8s.io "kube-dag" already existsError from server (AlreadyExists): error when creating "./deploy/setup-kubedag.y
aml": clusterrolebindings.rbac.authorization.k8s.io "kube-dag-role" already exists

root@kube-X580-G30:/usr/local/go/src/kubegene.io/kubegene# kubectl get pods
NAME                           READY     STATUS             RESTARTS   AGE
docker-demo-859795c745-tnnhw   0/1       ImagePullBackOff   0          4h
kube-dag-bc4f6bf68-k5bch       1/1       Running            0          38s

root@kube-X580-G30:/usr/local/go/src/kubegene.io/kubegene# kubectl get crd
NAME                               AGE
executions.execution.kubegene.io   58s
` 
During this time I think the important order of execution is "eval $(minikube docker-env)". Does it work? However, when I create a deployment with "kubectl run", the pod resrarts still is " ImagePullBackOff".

**Comment by xllbit** [comment]
@hzxuzhonghu **when I use "genectl describe" to query the detail info for workflow execution. The numbers of success is 0. And the state of kubectl-dag is "Running" or "CrashLoopBackOff" **
`root@kube-X580-G30:/usr/local/go/src/kubegene.io/kubegene# genectl describe exec
ution-129d1 -n defaultName:         execution-129d1
Namespace:    default
Labels:       <none>
Annotations:  <none>
Phase:        Running
workflow:
  joba(total: 2; success: 0; failed: 0; running: 0; error: 0):
    wait for execute
    Subtask  Phase  Message
    -------  -----  -------
  jobb(total: 3; success: 0; failed: 0; running: 0; error: 0):
    wait for execute
    Subtask  Phase  Message
    -------  -----  -------
  jobc(total: 2; success: 0; failed: 0; running: 0; error: 0):
    wait for execute
    Subtask  Phase  Message
    -------  -----  -------
  jobd(total: 2; success: 0; failed: 0; running: 0; error: 0):
    wait for execute
    Subtask  Phase  Message
    -------  -----  -------
  jobfinish(total: 1; success: 0; failed: 0; running: 0; error: 0):
    wait for execute
    Subtask  Phase  Message
    -------  -----  -------
  jobprepare(total: 1; success: 0; failed: 0; running: 0; error: 0):
    wait for execute
    Subtask  Phase  Message
    -------  -----  -------


root@kube-X580-G30:/usr/local/go/src/kubegene.io/kubegene# kubectl get pods
NAME                                 READY     STATUS             RESTARTS   AGE
execution-129d1.jobprepare.0-bxth2   0/1       Completed          0          7m
kube-dag-bc4f6bf68-lqxtc             0/1       CrashLoopBackOff   5          22m

root@kube-X580-G30:/usr/local/go/src/kubegene.io/kubegene# kubectl get pods
NAME                                 READY     STATUS      RESTARTS   AGE
execution-129d1.jobprepare.0-bxth2   0/1       Completed   0          8m
kube-dag-bc4f6bf68-lqxtc             1/1       Running     6          22m
`
**The logs of kube-dag is as follows:**
 `root@kube-X580-G30:/usr/local/go/src/kubegene.io/kubegene# kubectl logs kube-dag
-bc4f6bf68-lqxtcI1229 08:01:30.769186       1 flags.go:52] FLAG: --alsologtostderr="false"
I1229 08:01:30.769353       1 flags.go:52] FLAG: --kube-api-burst="30"
I1229 08:01:30.769365       1 flags.go:52] FLAG: --kube-api-qps="20"
I1229 08:01:30.769373       1 flags.go:52] FLAG: --kubeconfig=""
I1229 08:01:30.769381       1 flags.go:52] FLAG: --leader-elect="true"
I1229 08:01:30.769419       1 flags.go:52] FLAG: --lock-object-namespace="kube-s
ystem"I1229 08:01:30.769432       1 flags.go:52] FLAG: --log-backtrace-at=":0"
I1229 08:01:30.769441       1 flags.go:52] FLAG: --log-dir=""
I1229 08:01:30.769448       1 flags.go:52] FLAG: --log-flush-frequency="5s"
I1229 08:01:30.769458       1 flags.go:52] FLAG: --logtostderr="true"
I1229 08:01:30.769464       1 flags.go:52] FLAG: --resyncPeriod="1m0s"
I1229 08:01:30.769471       1 flags.go:52] FLAG: --stderrthreshold="2"
I1229 08:01:30.769478       1 flags.go:52] FLAG: --v="4"
I1229 08:01:30.769484       1 flags.go:52] FLAG: --vmodule=""
W1229 08:01:30.769502       1 client_config.go:548] Neither --kubeconfig nor --m
aster was specified.  Using the inClusterConfig.  This might not work.I1229 08:01:30.904901       1 leaderelection.go:187] attempting to acquire leade
r lease  kube-system/kubegene-controller...I1229 08:01:30.909568       1 leaderelection.go:271] lock is held by kube-dag-bc
4f6bf68-lqxtc_360ce16a-0b3f-11e9-81ff-0242ac110004 and has not yet expiredI1229 08:01:30.909807       1 leaderelection.go:192] failed to acquire lease kub
e-system/kubegene-controllerI1229 08:01:34.366294       1 leaderelection.go:271] lock is held by kube-dag-bc
4f6bf68-lqxtc_360ce16a-0b3f-11e9-81ff-0242ac110004 and has not yet expiredI1229 08:01:34.366563       1 leaderelection.go:192] failed to acquire lease kub
e-system/kubegene-controllerI1229 08:01:38.629197       1 leaderelection.go:271] lock is held by kube-dag-bc
4f6bf68-lqxtc_360ce16a-0b3f-11e9-81ff-0242ac110004 and has not yet expiredI1229 08:01:38.629253       1 leaderelection.go:192] failed to acquire lease kub
e-system/kubegene-controllerI1229 08:01:42.233823       1 leaderelection.go:271] lock is held by kube-dag-bc
4f6bf68-lqxtc_360ce16a-0b3f-11e9-81ff-0242ac110004 and has not yet expiredI1229 08:01:42.234200       1 leaderelection.go:192] failed to acquire lease kub
e-system/kubegene-controllerI1229 08:01:45.289634       1 leaderelection.go:271] lock is held by kube-dag-bc
4f6bf68-lqxtc_360ce16a-0b3f-11e9-81ff-0242ac110004 and has not yet expiredI1229 08:01:45.289678       1 leaderelection.go:192] failed to acquire lease kub
e-system/kubegene-controllerI1229 08:01:48.320322       1 leaderelection.go:196] successfully acquired lease
 kube-system/kubegene-controllerI1229 08:01:48.325704       1 controller.go:129] Starting execution controller
I1229 08:01:48.325763       1 event.go:221] Event(v1.ObjectReference{Kind:"Confi
gMap", Namespace:"kube-system", Name:"kubegene-controller", UID:"065b9a02-0b3c-11e9-b477-0800278b97b3", APIVersion:"v1", ResourceVersion:"3289", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' kube-dag-bc4f6bf68-lqxtc_f395fac4-0b3f-11e9-906b-0242ac110004 became leaderI1229 08:01:48.327099       1 reflector.go:131] Starting reflector *v1.Job (1m0s
) from k8s.io/client-go/informers/factory.go:131I1229 08:01:48.327151       1 reflector.go:169] Listing and watching *v1.Job fro
m k8s.io/client-go/informers/factory.go:131I1229 08:01:48.327528       1 reflector.go:131] Starting reflector *v1alpha1.Exe
cution (1m0s) from kubegene.io/kubegene/pkg/client/informers/externalversions/factory.go:117I1229 08:01:48.327543       1 reflector.go:169] Listing and watching *v1alpha1.E
xecution from kubegene.io/kubegene/pkg/client/informers/externalversions/factory.go:117I1229 08:01:48.334239       1 leaderelection.go:227] successfully renewed lease 
kube-system/kubegene-controllerI1229 08:01:48.426099       1 shared_informer.go:123] caches populated
I1229 08:01:48.426297       1 util.go:123] execution default/execution-129d1 pha
se  -> ErrorI1229 08:01:48.426652       1 controller.go:162] execution default/execution-129
d1 enter syncI1229 08:01:48.426973       1 controller.go:351] Started syncing execution "defa
ult/execution-129d1" (2018-12-29 08:01:48.426962322 +0000 UTC m=+17.673926242)I1229 08:01:48.427242       1 execution_job.go:91] Starting execution job contro
llerI1229 08:01:48.427731       1 controller.go:382] generate graph for execution de
fault/execution-129d1I1229 08:01:48.428121       1 controller.go:353] Finished syncing execution "def
ault/execution-129d1" (1.152492ms)I1229 08:01:48.428205       1 execution_job.go:148] execution default/execution-
129d1 start running.I1229 08:01:48.445260       1 controller.go:252] update execution default/execut
ion-129d1.jobprepare.0 status error: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:""}, Status:"Failure", Message:"the server could not find the requested resource (put executions.execution.kubegene.io execution-129d1)", Reason:"NotFound", Details:(*v1.StatusDetails)(0xc0000d5860), Code:404}}I1229 08:01:48.445337       1 controller.go:202] Finished syncing job "default/e
xecution-129d1.jobprepare.0" (19.141094ms)E1229 08:01:48.445355       1 controller.go:193] error syncing job: the server c
ould not find the requested resource (put executions.execution.kubegene.io execution-129d1)I1229 08:01:48.451517       1 controller.go:202] Finished syncing job "default/e
xecution-129d1.jobprepare.0" (90.602µs)E1229 08:01:48.451874       1 runtime.go:66] Observed a panic: "can not get stat
us fot vertex execution-129d1.jobprepare.0" (can not get status fot vertex execution-129d1.jobprepare.0)/usr/local/go/src/kubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/util/runti
me/runtime.go:72/usr/local/go/src/kubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/util/runti
me/runtime.go:65/usr/local/go/src/kubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/util/runti
me/runtime.go:51/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/usr/local/go/src/kubegene.io/kubegene/pkg/util/util.go:173
/usr/local/go/src/kubegene.io/kubegene/pkg/util/util.go:149
/usr/local/go/src/kubegene.io/kubegene/pkg/controller/controller.go:299
/usr/local/go/src/kubegene.io/kubegene/pkg/controller/controller.go:114
/usr/local/go/src/kubegene.io/kubegene/pkg/controller/controller.go:185
/usr/local/go/src/kubegene.io/kubegene/pkg/controller/controller.go:174
/usr/local/go/src/kubegene.io/kubegene/pkg/controller/controller.go:142
/usr/local/go/src/kubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/util/wait/
wait.go:133/usr/local/go/src/kubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/util/wait/
wait.go:134/usr/local/go/src/kubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/util/wait/
wait.go:88/usr/local/go/src/runtime/asm_amd64.s:1333
panic: can not get status fot vertex execution-129d1.jobprepare.0 [recovered]
	panic: can not get status fot vertex execution-129d1.jobprepare.0

goroutine 39 [running]:
kubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0
, 0x0, 0x0)	/usr/local/go/src/kubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/ut
il/runtime/runtime.go:58 +0x108panic(0x1064d00, 0xc00022b440)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
kubegene.io/kubegene/pkg/util.MarkVertexPhase(0xc000100a80, 0xc000676440, 0x1c, 
0x120f349, 0x9, 0x120e43a, 0x7)	/usr/local/go/src/kubegene.io/kubegene/pkg/util/util.go:173 +0x5ff
kubegene.io/kubegene/pkg/util.MarkVertexSuccess(0xc000100a80, 0xc000676440, 0x1c
, 0x120e43a, 0x7)	/usr/local/go/src/kubegene.io/kubegene/pkg/util/util.go:149 +0x68
kubegene.io/kubegene/pkg/controller.(*ExecutionController).syncJob(0xc000383c80,
 0xc00047a540, 0x24, 0xc0006a9e00, 0x0, 0x0)	/usr/local/go/src/kubegene.io/kubegene/pkg/controller/controller.go:299 
+0x5fekubegene.io/kubegene/pkg/controller.(*ExecutionController).syncJob-fm(0xc00047a5
40, 0x24, 0xc0004807c0, 0x1064d00, 0xc0002ceab0)	/usr/local/go/src/kubegene.io/kubegene/pkg/controller/controller.go:114 
+0x3ekubegene.io/kubegene/pkg/controller.(*ExecutionController).processNextJobItem(0x
c000383c80, 0xc000320000)	/usr/local/go/src/kubegene.io/kubegene/pkg/controller/controller.go:185 
+0xd5kubegene.io/kubegene/pkg/controller.(*ExecutionController).jobWorker(0xc000383c8
0)	/usr/local/go/src/kubegene.io/kubegene/pkg/controller/controller.go:174 
+0x2bkubegene.io/kubegene/pkg/controller.(*ExecutionController).jobWorker-fm()
	/usr/local/go/src/kubegene.io/kubegene/pkg/controller/controller.go:142 
+0x2akubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(
0xc00046c010)	/usr/local/go/src/kubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/ut
il/wait/wait.go:133 +0x54kubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000
46c010, 0x3b9aca00, 0x0, 0xc00021d401, 0xc0000966c0)	/usr/local/go/src/kubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/ut
il/wait/wait.go:134 +0xbekubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00046c010
, 0x3b9aca00, 0xc0000966c0)	/usr/local/go/src/kubegene.io/kubegene/vendor/k8s.io/apimachinery/pkg/ut
il/wait/wait.go:88 +0x4dcreated by kubegene.io/kubegene/pkg/controller.(*ExecutionController).Run
	/usr/local/go/src/kubegene.io/kubegene/pkg/controller/controller.go:142 
+0x1ec`
And this is the new project that I git clone this afternoon.

**Comment by hzxuzhonghu** [comment]
After a deep look, I think the root cause is that kube-dag missed job event(why it miss is unknown ).   But as k8s is a eventual consistent system. It does guarantee all events received by client. So we should  modify here , instead of panic, we should init it like `ExecutionController.syncJob`
```
	if vertexStatus == nil {
		panic(fmt.Sprintf("can not get status fot vertex %s", vertexName))
	}

```

**Comment by hzxuzhonghu** [comment]
@wackxu

**Comment by xllbit** [comment]
the yaml is simple-sample.yaml. I just tried it with README.md and modified nothing.

**Comment by xllbit** [comment]
There is a mistake in README.md. the file path is wrong.
$ kubectl create -f example/simale-sample/sample-pv.yaml
$ kubectl create -f example/simale-sample/sample-pvc.yaml
should be 
$ kubectl create -f example/simple-sample/sample-pv.yaml
$ kubectl create -f example/simple-sample/sample-pvc.yaml

**Comment by hzxuzhonghu** [comment]
Thanks @xllbit , would you help fix it?

**Comment by xllbit** [comment]
@hzxuzhonghu ok, I will
