### ISSUE TITLE
indicate explicit resource type for genectl describe

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kubegene/kubegene#32]
`genectl describe` command is now implemented with implict and fixed resource type:
`genectl describe <resource name>` actually means `genectl describe execution <resource name>`.

To address this issue, the command format shall be
```
genectl describe <resource type> <resource name>
```
Or
```
genectl describe <resource type>/<resource name>
```

**Comment by SrinivasChilveri** [comment]
Its better change the del command also.
At present it is 
genectl del executionName [flags]  

to genectl del execution  executionName [flags]
