### ISSUE TITLE
add If-else & Switch-case ability to KubeGene 

### ISSUE THREAD

**Issue by tsjsdbd** [kubegene/kubegene#57]
we need add the Func:  
get_result()  
check_resule()

**Comment by SrinivasChilveri** [comment]
@tsjsdbd , the get_result & check_result features are already added.

The related PRs are

https://github.com/kubegene/kubegene/pull/43
https://github.com/kubegene/kubegene/pull/47

even added some generic conditional handling as

https://github.com/kubegene/kubegene/pull/52.

are you expecting something else? please do let me know.

**Comment by SrinivasChilveri** [comment]
I am closing this issue as these features are already implemented.
please feel free to open if required.
