### ISSUE TITLE
kubegene.io和kubegene.netlify.com域名失效

### ISSUE THREAD

**Issue by Enokiy** [kubegene/kubegene#67]
https://kubegene.netlify.com/docs/guides/workflow-grammar
https://kubegene.io/docs/about/kubegene/  说明里的链接无法打开，域名过期了？

**Comment by kevin-wangzefeng** [comment]
谢谢提醒，是域名到期了，已修复

**Comment by Enokiy** [comment]
问题已修复，3Q
